### ISSUE TITLE
Already published

### ISSUE THREAD

**Issue by mbest** [Duder-onomy/parse-keys-and-values-from-object-literal-strings#1]
I've already published this (it's my code): https://github.com/mbest/js-object-literal-parse
https://www.npmjs.com/package/object-literal-parse

**Comment by Duder-onomy** [comment]
No Prob. 
Looks like you got it from the same place as I. 
Or maybe `knockout.js` took it from you? Either way, I def did not write it. 
I no longer use the library that was consuming this. 
What would you like me to do with this repo?

**Comment by mbest** [comment]
Yes, Knockout got it from me. Perhaps, just provide a link to my repo in your README.

**Comment by Duder-onomy** [comment]
Cool. 
It's done. I deprecated it on NPM, and I put a note in the Readme. 
Thanks for your work!
